name: mytv

on:
  schedule:
    - cron: '0 9,21 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run search
        run: python ${{ github.workspace }}/temp/search.py

      #- name: Run cctv
        #run: python ${{ github.workspace }}/cctv.py
        
      #- name: Run weishi
        #run: python ${{ github.workspace }}/weishi.py
        
      #- name: Run qita
        #run: python ${{ github.workspace }}/qita.py
        
      - name: 提交更改
        run: |
          git config --local user.email "2729189723@qq.com"
          git config --local user.name "xiaoluo0226"
          git add .
          git commit mytv.txt -m "Add generated file"
          git commit mytv.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
